version: 1
formatters:
  simple:
    format: '%(asctime)s %(levelname)s %(name)s (%(pathname)s:%(lineno)d): %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  __main__:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: WARN
  handlers: [console]
disable_existing_loggers: False
